// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 001_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, type, currency, opening_balance, credit_limit, statement_day, payment_due_day)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, user_id, name, type, currency, opening_balance, credit_limit, statement_day, payment_due_day, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	UserID         pgtype.UUID    `json:"user_id"`
	Name           string         `json:"name"`
	Type           AccountType    `json:"type"`
	Currency       string         `json:"currency"`
	OpeningBalance pgtype.Numeric `json:"opening_balance"`
	CreditLimit    pgtype.Numeric `json:"credit_limit"`
	StatementDay   pgtype.Numeric `json:"statement_day"`
	PaymentDueDay  pgtype.Numeric `json:"payment_due_day"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.CreditLimit,
		arg.StatementDay,
		arg.PaymentDueDay,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.CreditLimit,
		&i.StatementDay,
		&i.PaymentDueDay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, name, amount, currency, period_type, start_date, end_date, period_anchor_date, rollover)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, category_id, name, amount, currency, period_type, start_date, end_date, period_anchor_date, rollover, created_at, updated_at, deleted_at
`

type CreateBudgetParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	CategoryID       pgtype.UUID    `json:"category_id"`
	Name             string         `json:"name"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	PeriodType       PeriodType     `json:"period_type"`
	StartDate        pgtype.Date    `json:"start_date"`
	EndDate          pgtype.Date    `json:"end_date"`
	PeriodAnchorDate pgtype.Date    `json:"period_anchor_date"`
	Rollover         bool           `json:"rollover"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.PeriodType,
		arg.StartDate,
		arg.EndDate,
		arg.PeriodAnchorDate,
		arg.Rollover,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.PeriodType,
		&i.StartDate,
		&i.EndDate,
		&i.PeriodAnchorDate,
		&i.Rollover,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, type, icon, color)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, name, type, icon, color, deleted_at
`

type CreateCategoryParams struct {
	UserID pgtype.UUID  `json:"user_id"`
	Name   string       `json:"name"`
	Type   CategoryType `json:"type"`
	Icon   pgtype.Text  `json:"icon"`
	Color  pgtype.Text  `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
	)
	return i, err
}

const createCategoryKeyword = `-- name: CreateCategoryKeyword :one
INSERT INTO category_keywords (user_id, category_id, keyword)
VALUES ($1, $2, $3) RETURNING id, user_id, category_id, keyword, created_at
`

type CreateCategoryKeywordParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Keyword    string      `json:"keyword"`
}

func (q *Queries) CreateCategoryKeyword(ctx context.Context, arg CreateCategoryKeywordParams) (CategoryKeyword, error) {
	row := q.db.QueryRow(ctx, createCategoryKeyword, arg.UserID, arg.CategoryID, arg.Keyword)
	var i CategoryKeyword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Keyword,
		&i.CreatedAt,
	)
	return i, err
}

const createInsurancePayment = `-- name: CreateInsurancePayment :one
INSERT INTO insurance_payments (policy_id, date, amount, status)
VALUES ($1, $2, $3, $4) RETURNING id, policy_id, date, amount, status, created_at, deleted_at
`

type CreateInsurancePaymentParams struct {
	PolicyID pgtype.UUID            `json:"policy_id"`
	Date     pgtype.Date            `json:"date"`
	Amount   pgtype.Numeric         `json:"amount"`
	Status   InsurancePaymentStatus `json:"status"`
}

func (q *Queries) CreateInsurancePayment(ctx context.Context, arg CreateInsurancePaymentParams) (InsurancePayment, error) {
	row := q.db.QueryRow(ctx, createInsurancePayment,
		arg.PolicyID,
		arg.Date,
		arg.Amount,
		arg.Status,
	)
	var i InsurancePayment
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Date,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInsurancePolicy = `-- name: CreateInsurancePolicy :one
INSERT INTO insurance_policies (user_id, name, provider, policy_type, premium_amount, premium_frequency, coverage_amount, currency, start_date, end_date, renewal_date, nominee, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id, user_id, name, provider, policy_type, premium_amount, premium_frequency, coverage_amount, currency, start_date, end_date, renewal_date, nominee, notes, created_at, updated_at, deleted_at
`

type CreateInsurancePolicyParams struct {
	UserID           pgtype.UUID      `json:"user_id"`
	Name             string           `json:"name"`
	Provider         pgtype.Text      `json:"provider"`
	PolicyType       PolicyType       `json:"policy_type"`
	PremiumAmount    pgtype.Numeric   `json:"premium_amount"`
	PremiumFrequency PremiumFrequency `json:"premium_frequency"`
	CoverageAmount   pgtype.Numeric   `json:"coverage_amount"`
	Currency         string           `json:"currency"`
	StartDate        pgtype.Date      `json:"start_date"`
	EndDate          pgtype.Date      `json:"end_date"`
	RenewalDate      pgtype.Date      `json:"renewal_date"`
	Nominee          pgtype.Text      `json:"nominee"`
	Notes            pgtype.Text      `json:"notes"`
}

func (q *Queries) CreateInsurancePolicy(ctx context.Context, arg CreateInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, createInsurancePolicy,
		arg.UserID,
		arg.Name,
		arg.Provider,
		arg.PolicyType,
		arg.PremiumAmount,
		arg.PremiumFrequency,
		arg.CoverageAmount,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.RenewalDate,
		arg.Nominee,
		arg.Notes,
	)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.PolicyType,
		&i.PremiumAmount,
		&i.PremiumFrequency,
		&i.CoverageAmount,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.RenewalDate,
		&i.Nominee,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (user_id, name, asset_type, currency, quantity, buy_price, current_price, current_price_updated_at, maturity_date, interest_rate, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, user_id, name, asset_type, currency, quantity, buy_price, current_price, current_price_updated_at, maturity_date, interest_rate, metadata, created_at, updated_at, deleted_at
`

type CreateInvestmentParams struct {
	UserID                pgtype.UUID        `json:"user_id"`
	Name                  string             `json:"name"`
	AssetType             AssetType          `json:"asset_type"`
	Currency              string             `json:"currency"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	BuyPrice              pgtype.Numeric     `json:"buy_price"`
	CurrentPrice          pgtype.Numeric     `json:"current_price"`
	CurrentPriceUpdatedAt pgtype.Timestamptz `json:"current_price_updated_at"`
	MaturityDate          pgtype.Date        `json:"maturity_date"`
	InterestRate          pgtype.Numeric     `json:"interest_rate"`
	Metadata              []byte             `json:"metadata"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.UserID,
		arg.Name,
		arg.AssetType,
		arg.Currency,
		arg.Quantity,
		arg.BuyPrice,
		arg.CurrentPrice,
		arg.CurrentPriceUpdatedAt,
		arg.MaturityDate,
		arg.InterestRate,
		arg.Metadata,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.Currency,
		&i.Quantity,
		&i.BuyPrice,
		&i.CurrentPrice,
		&i.CurrentPriceUpdatedAt,
		&i.MaturityDate,
		&i.InterestRate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvestmentTx = `-- name: CreateInvestmentTx :one
INSERT INTO investment_transactions (investment_id, type, quantity, price, amount, date, note)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, investment_id, type, quantity, price, amount, date, note, created_at, deleted_at
`

type CreateInvestmentTxParams struct {
	InvestmentID pgtype.UUID      `json:"investment_id"`
	Type         InvestmentTxType `json:"type"`
	Quantity     pgtype.Numeric   `json:"quantity"`
	Price        pgtype.Numeric   `json:"price"`
	Amount       pgtype.Numeric   `json:"amount"`
	Date         pgtype.Date      `json:"date"`
	Note         pgtype.Text      `json:"note"`
}

func (q *Queries) CreateInvestmentTx(ctx context.Context, arg CreateInvestmentTxParams) (InvestmentTransaction, error) {
	row := q.db.QueryRow(ctx, createInvestmentTx,
		arg.InvestmentID,
		arg.Type,
		arg.Quantity,
		arg.Price,
		arg.Amount,
		arg.Date,
		arg.Note,
	)
	var i InvestmentTransaction
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Amount,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (user_id, name, loan_type, principal, interest_rate, tenure_months, start_date, emi_amount, currency, outstanding_balance)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, name, loan_type, principal, interest_rate, tenure_months, start_date, emi_amount, currency, outstanding_balance, created_at, updated_at, deleted_at
`

type CreateLoanParams struct {
	UserID             pgtype.UUID    `json:"user_id"`
	Name               string         `json:"name"`
	LoanType           LoanType       `json:"loan_type"`
	Principal          pgtype.Numeric `json:"principal"`
	InterestRate       pgtype.Numeric `json:"interest_rate"`
	TenureMonths       int32          `json:"tenure_months"`
	StartDate          pgtype.Date    `json:"start_date"`
	EmiAmount          pgtype.Numeric `json:"emi_amount"`
	Currency           string         `json:"currency"`
	OutstandingBalance pgtype.Numeric `json:"outstanding_balance"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.UserID,
		arg.Name,
		arg.LoanType,
		arg.Principal,
		arg.InterestRate,
		arg.TenureMonths,
		arg.StartDate,
		arg.EmiAmount,
		arg.Currency,
		arg.OutstandingBalance,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LoanType,
		&i.Principal,
		&i.InterestRate,
		&i.TenureMonths,
		&i.StartDate,
		&i.EmiAmount,
		&i.Currency,
		&i.OutstandingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLoanPayment = `-- name: CreateLoanPayment :one
INSERT INTO loan_payments (loan_id, date, amount, principal_component, interest_component, status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, loan_id, date, amount, principal_component, interest_component, status, created_at, deleted_at
`

type CreateLoanPaymentParams struct {
	LoanID             pgtype.UUID    `json:"loan_id"`
	Date               pgtype.Date    `json:"date"`
	Amount             pgtype.Numeric `json:"amount"`
	PrincipalComponent pgtype.Numeric `json:"principal_component"`
	InterestComponent  pgtype.Numeric `json:"interest_component"`
	Status             PaymentStatus  `json:"status"`
}

func (q *Queries) CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error) {
	row := q.db.QueryRow(ctx, createLoanPayment,
		arg.LoanID,
		arg.Date,
		arg.Amount,
		arg.PrincipalComponent,
		arg.InterestComponent,
		arg.Status,
	)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Date,
		&i.Amount,
		&i.PrincipalComponent,
		&i.InterestComponent,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (user_id, name, description, target_amount, currency, current_amount, linked_account_id, deadline, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, user_id, name, description, target_amount, currency, current_amount, linked_account_id, deadline, status, created_at, updated_at, deleted_at
`

type CreateSavingsGoalParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	TargetAmount    pgtype.Numeric `json:"target_amount"`
	Currency        string         `json:"currency"`
	CurrentAmount   pgtype.Numeric `json:"current_amount"`
	LinkedAccountID pgtype.UUID    `json:"linked_account_id"`
	Deadline        pgtype.Date    `json:"deadline"`
	Status          GoalStatus     `json:"status"`
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.TargetAmount,
		arg.Currency,
		arg.CurrentAmount,
		arg.LinkedAccountID,
		arg.Deadline,
		arg.Status,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.Currency,
		&i.CurrentAmount,
		&i.LinkedAccountID,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name, color) VALUES ($1, $2, $3) RETURNING id, user_id, name, color
`

type CreateTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Color  pgtype.Text `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, account_id, type, amount, currency, converted_amount, base_currency, category_id, title, note, date, is_recurring, recurrence_rule, recurrence_interval, recurrence_unit, parent_recurring_id, transfer_to_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING id, user_id, account_id, type, amount, currency, converted_amount, base_currency, category_id, title, note, date, is_recurring, recurrence_rule, recurrence_interval, recurrence_unit, parent_recurring_id, transfer_to_id, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID             pgtype.UUID     `json:"user_id"`
	AccountID          pgtype.UUID     `json:"account_id"`
	Type               TransactionType `json:"type"`
	Amount             pgtype.Numeric  `json:"amount"`
	Currency           string          `json:"currency"`
	ConvertedAmount    pgtype.Numeric  `json:"converted_amount"`
	BaseCurrency       pgtype.Text     `json:"base_currency"`
	CategoryID         pgtype.UUID     `json:"category_id"`
	Title              pgtype.Text     `json:"title"`
	Note               pgtype.Text     `json:"note"`
	Date               pgtype.Date     `json:"date"`
	IsRecurring        bool            `json:"is_recurring"`
	RecurrenceRule     pgtype.Text     `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric  `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text     `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID     `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID     `json:"transfer_to_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.ConvertedAmount,
		arg.BaseCurrency,
		arg.CategoryID,
		arg.Title,
		arg.Note,
		arg.Date,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.RecurrenceInterval,
		arg.RecurrenceUnit,
		arg.ParentRecurringID,
		arg.TransferToID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.ConvertedAmount,
		&i.BaseCurrency,
		&i.CategoryID,
		&i.Title,
		&i.Note,
		&i.Date,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.RecurrenceInterval,
		&i.RecurrenceUnit,
		&i.ParentRecurringID,
		&i.TransferToID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, default_currency, timezone)
VALUES ($1, $2, $3, $4, $5) RETURNING id, email, password_hash, name, default_currency, timezone, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email           string `json:"email"`
	PasswordHash    string `json:"password_hash"`
	Name            string `json:"name"`
	DefaultCurrency string `json:"default_currency"`
	Timezone        string `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.DefaultCurrency,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const deleteBudget = `-- name: DeleteBudget :exec
UPDATE budgets SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.Exec(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const deleteCategoryKeyword = `-- name: DeleteCategoryKeyword :exec
DELETE FROM category_keywords WHERE id = $1 AND user_id = $2
`

type DeleteCategoryKeywordParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategoryKeyword(ctx context.Context, arg DeleteCategoryKeywordParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryKeyword, arg.ID, arg.UserID)
	return err
}

const deleteInsurancePolicy = `-- name: DeleteInsurancePolicy :exec
UPDATE insurance_policies SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteInsurancePolicyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteInsurancePolicy(ctx context.Context, arg DeleteInsurancePolicyParams) error {
	_, err := q.db.Exec(ctx, deleteInsurancePolicy, arg.ID, arg.UserID)
	return err
}

const deleteInvestment = `-- name: DeleteInvestment :exec
UPDATE investments SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteInvestmentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteInvestment(ctx context.Context, arg DeleteInvestmentParams) error {
	_, err := q.db.Exec(ctx, deleteInvestment, arg.ID, arg.UserID)
	return err
}

const deleteLoan = `-- name: DeleteLoan :exec
UPDATE loans SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteLoanParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteLoan(ctx context.Context, arg DeleteLoanParams) error {
	_, err := q.db.Exec(ctx, deleteLoan, arg.ID, arg.UserID)
	return err
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :exec
UPDATE savings_goals SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteSavingsGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsGoal, arg.ID, arg.UserID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
UPDATE transactions SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, type, currency, opening_balance, credit_limit, statement_day, payment_due_day, created_at, updated_at, deleted_at FROM accounts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.CreditLimit,
		&i.StatementDay,
		&i.PaymentDueDay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, category_id, name, amount, currency, period_type, start_date, end_date, period_anchor_date, rollover, created_at, updated_at, deleted_at FROM budgets WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBudgetByID(ctx context.Context, id pgtype.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.PeriodType,
		&i.StartDate,
		&i.EndDate,
		&i.PeriodAnchorDate,
		&i.Rollover,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, type, icon, color, deleted_at FROM categories WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
	)
	return i, err
}

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT base, target, rate, fetched_at FROM exchange_rates WHERE base = $1 AND target = $2
`

type GetExchangeRateParams struct {
	Base   string `json:"base"`
	Target string `json:"target"`
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRate, arg.Base, arg.Target)
	var i ExchangeRate
	err := row.Scan(
		&i.Base,
		&i.Target,
		&i.Rate,
		&i.FetchedAt,
	)
	return i, err
}

const getExpensesByPeriod = `-- name: GetExpensesByPeriod :many
SELECT t.id, t.user_id, t.account_id, t.type, t.amount, t.currency, t.converted_amount, t.base_currency, t.category_id, t.title, t.note, t.date, t.is_recurring, t.recurrence_rule, t.recurrence_interval, t.recurrence_unit, t.parent_recurring_id, t.transfer_to_id, t.created_at, t.updated_at, t.deleted_at, c.name as category_name
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL AND t.type = 'expense'
  AND t.date >= $2 AND t.date <= $3
ORDER BY t.date
`

type GetExpensesByPeriodParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetExpensesByPeriodRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	Type               TransactionType    `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ConvertedAmount    pgtype.Numeric     `json:"converted_amount"`
	BaseCurrency       pgtype.Text        `json:"base_currency"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Title              pgtype.Text        `json:"title"`
	Note               pgtype.Text        `json:"note"`
	Date               pgtype.Date        `json:"date"`
	IsRecurring        bool               `json:"is_recurring"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric     `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text        `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID        `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID        `json:"transfer_to_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CategoryName       pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetExpensesByPeriod(ctx context.Context, arg GetExpensesByPeriodParams) ([]GetExpensesByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getExpensesByPeriod, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpensesByPeriodRow{}
	for rows.Next() {
		var i GetExpensesByPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.ConvertedAmount,
			&i.BaseCurrency,
			&i.CategoryID,
			&i.Title,
			&i.Note,
			&i.Date,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceInterval,
			&i.RecurrenceUnit,
			&i.ParentRecurringID,
			&i.TransferToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomeByPeriod = `-- name: GetIncomeByPeriod :many
SELECT t.id, t.user_id, t.account_id, t.type, t.amount, t.currency, t.converted_amount, t.base_currency, t.category_id, t.title, t.note, t.date, t.is_recurring, t.recurrence_rule, t.recurrence_interval, t.recurrence_unit, t.parent_recurring_id, t.transfer_to_id, t.created_at, t.updated_at, t.deleted_at, c.name as category_name
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL AND t.type = 'income'
  AND t.date >= $2 AND t.date <= $3
ORDER BY t.date
`

type GetIncomeByPeriodParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetIncomeByPeriodRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	Type               TransactionType    `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ConvertedAmount    pgtype.Numeric     `json:"converted_amount"`
	BaseCurrency       pgtype.Text        `json:"base_currency"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Title              pgtype.Text        `json:"title"`
	Note               pgtype.Text        `json:"note"`
	Date               pgtype.Date        `json:"date"`
	IsRecurring        bool               `json:"is_recurring"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric     `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text        `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID        `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID        `json:"transfer_to_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CategoryName       pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetIncomeByPeriod(ctx context.Context, arg GetIncomeByPeriodParams) ([]GetIncomeByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getIncomeByPeriod, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIncomeByPeriodRow{}
	for rows.Next() {
		var i GetIncomeByPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.ConvertedAmount,
			&i.BaseCurrency,
			&i.CategoryID,
			&i.Title,
			&i.Note,
			&i.Date,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceInterval,
			&i.RecurrenceUnit,
			&i.ParentRecurringID,
			&i.TransferToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsurancePolicyByID = `-- name: GetInsurancePolicyByID :one
SELECT id, user_id, name, provider, policy_type, premium_amount, premium_frequency, coverage_amount, currency, start_date, end_date, renewal_date, nominee, notes, created_at, updated_at, deleted_at FROM insurance_policies WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInsurancePolicyByID(ctx context.Context, id pgtype.UUID) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, getInsurancePolicyByID, id)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.PolicyType,
		&i.PremiumAmount,
		&i.PremiumFrequency,
		&i.CoverageAmount,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.RenewalDate,
		&i.Nominee,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, user_id, name, asset_type, currency, quantity, buy_price, current_price, current_price_updated_at, maturity_date, interest_rate, metadata, created_at, updated_at, deleted_at FROM investments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInvestmentByID(ctx context.Context, id pgtype.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.Currency,
		&i.Quantity,
		&i.BuyPrice,
		&i.CurrentPrice,
		&i.CurrentPriceUpdatedAt,
		&i.MaturityDate,
		&i.InterestRate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, user_id, name, loan_type, principal, interest_rate, tenure_months, start_date, emi_amount, currency, outstanding_balance, created_at, updated_at, deleted_at FROM loans WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LoanType,
		&i.Principal,
		&i.InterestRate,
		&i.TenureMonths,
		&i.StartDate,
		&i.EmiAmount,
		&i.Currency,
		&i.OutstandingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.user_id, t.account_id, t.type, t.amount, t.currency, t.converted_amount, t.base_currency, t.category_id, t.title, t.note, t.date, t.is_recurring, t.recurrence_rule, t.recurrence_interval, t.recurrence_unit, t.parent_recurring_id, t.transfer_to_id, t.created_at, t.updated_at, t.deleted_at, a.name as account_name, c.name as category_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTransactionByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	Type               TransactionType    `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ConvertedAmount    pgtype.Numeric     `json:"converted_amount"`
	BaseCurrency       pgtype.Text        `json:"base_currency"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Title              pgtype.Text        `json:"title"`
	Note               pgtype.Text        `json:"note"`
	Date               pgtype.Date        `json:"date"`
	IsRecurring        bool               `json:"is_recurring"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric     `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text        `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID        `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID        `json:"transfer_to_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	AccountName        string             `json:"account_name"`
	CategoryName       pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.ConvertedAmount,
		&i.BaseCurrency,
		&i.CategoryID,
		&i.Title,
		&i.Note,
		&i.Date,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.RecurrenceInterval,
		&i.RecurrenceUnit,
		&i.ParentRecurringID,
		&i.TransferToID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountName,
		&i.CategoryName,
	)
	return i, err
}

const getTransactionTags = `-- name: GetTransactionTags :many
SELECT tg.id, tg.user_id, tg.name, tg.color FROM tags tg
JOIN transaction_tags tt ON tt.tag_id = tg.id
WHERE tt.transaction_id = $1
`

func (q *Queries) GetTransactionTags(ctx context.Context, transactionID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTransactionTags, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByDateRange = `-- name: GetTransactionsByDateRange :many
SELECT t.id, t.user_id, t.account_id, t.type, t.amount, t.currency, t.converted_amount, t.base_currency, t.category_id, t.title, t.note, t.date, t.is_recurring, t.recurrence_rule, t.recurrence_interval, t.recurrence_unit, t.parent_recurring_id, t.transfer_to_id, t.created_at, t.updated_at, t.deleted_at, a.name as account_name, c.name as category_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL
  AND t.date >= $2 AND t.date <= $3
ORDER BY t.date DESC
`

type GetTransactionsByDateRangeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetTransactionsByDateRangeRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	Type               TransactionType    `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ConvertedAmount    pgtype.Numeric     `json:"converted_amount"`
	BaseCurrency       pgtype.Text        `json:"base_currency"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Title              pgtype.Text        `json:"title"`
	Note               pgtype.Text        `json:"note"`
	Date               pgtype.Date        `json:"date"`
	IsRecurring        bool               `json:"is_recurring"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric     `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text        `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID        `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID        `json:"transfer_to_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	AccountName        string             `json:"account_name"`
	CategoryName       pgtype.Text        `json:"category_name"`
}

// Summary / aggregation queries
func (q *Queries) GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]GetTransactionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsByDateRangeRow{}
	for rows.Next() {
		var i GetTransactionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.ConvertedAmount,
			&i.BaseCurrency,
			&i.CategoryID,
			&i.Title,
			&i.Note,
			&i.Date,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceInterval,
			&i.RecurrenceUnit,
			&i.ParentRecurringID,
			&i.TransferToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, default_currency, timezone, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, default_currency, timezone, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

// Users
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, type, currency, opening_balance, credit_limit, statement_day, payment_due_day, created_at, updated_at, deleted_at FROM accounts WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

// Accounts
func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.OpeningBalance,
			&i.CreditLimit,
			&i.StatementDay,
			&i.PaymentDueDay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByUser = `-- name: ListBudgetsByUser :many
SELECT b.id, b.user_id, b.category_id, b.name, b.amount, b.currency, b.period_type, b.start_date, b.end_date, b.period_anchor_date, b.rollover, b.created_at, b.updated_at, b.deleted_at, c.name as category_name, c.color as category_color
FROM budgets b
LEFT JOIN categories c ON c.id = b.category_id
WHERE b.user_id = $1 AND b.deleted_at IS NULL ORDER BY b.name
`

type ListBudgetsByUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	PeriodType       PeriodType         `json:"period_type"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	PeriodAnchorDate pgtype.Date        `json:"period_anchor_date"`
	Rollover         bool               `json:"rollover"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CategoryName     pgtype.Text        `json:"category_name"`
	CategoryColor    pgtype.Text        `json:"category_color"`
}

// Budgets
func (q *Queries) ListBudgetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListBudgetsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsByUserRow{}
	for rows.Next() {
		var i ListBudgetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.PeriodType,
			&i.StartDate,
			&i.EndDate,
			&i.PeriodAnchorDate,
			&i.Rollover,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT id, user_id, name, type, icon, color, deleted_at FROM categories WHERE (user_id = $1 OR user_id IS NULL) AND deleted_at IS NULL ORDER BY name
`

// Categories
func (q *Queries) ListCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryKeywordsByUser = `-- name: ListCategoryKeywordsByUser :many
SELECT ck.id, ck.user_id, ck.category_id, ck.keyword, ck.created_at, c.name as category_name FROM category_keywords ck
JOIN categories c ON c.id = ck.category_id
WHERE ck.user_id = $1 ORDER BY ck.keyword
`

type ListCategoryKeywordsByUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Keyword      string             `json:"keyword"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName string             `json:"category_name"`
}

// Category Keywords (for auto-categorisation)
func (q *Queries) ListCategoryKeywordsByUser(ctx context.Context, userID pgtype.UUID) ([]ListCategoryKeywordsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCategoryKeywordsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryKeywordsByUserRow{}
	for rows.Next() {
		var i ListCategoryKeywordsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Keyword,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT base, target, rate, fetched_at FROM exchange_rates ORDER BY base, target
`

func (q *Queries) ListExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.Base,
			&i.Target,
			&i.Rate,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsurancePayments = `-- name: ListInsurancePayments :many
SELECT id, policy_id, date, amount, status, created_at, deleted_at FROM insurance_payments WHERE policy_id = $1 AND deleted_at IS NULL ORDER BY date DESC
`

// Insurance Payments
func (q *Queries) ListInsurancePayments(ctx context.Context, policyID pgtype.UUID) ([]InsurancePayment, error) {
	rows, err := q.db.Query(ctx, listInsurancePayments, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsurancePayment{}
	for rows.Next() {
		var i InsurancePayment
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Date,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsurancePoliciesByUser = `-- name: ListInsurancePoliciesByUser :many
SELECT id, user_id, name, provider, policy_type, premium_amount, premium_frequency, coverage_amount, currency, start_date, end_date, renewal_date, nominee, notes, created_at, updated_at, deleted_at FROM insurance_policies WHERE user_id = $1 AND deleted_at IS NULL ORDER BY name
`

// Insurance Policies
func (q *Queries) ListInsurancePoliciesByUser(ctx context.Context, userID pgtype.UUID) ([]InsurancePolicy, error) {
	rows, err := q.db.Query(ctx, listInsurancePoliciesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsurancePolicy{}
	for rows.Next() {
		var i InsurancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.PolicyType,
			&i.PremiumAmount,
			&i.PremiumFrequency,
			&i.CoverageAmount,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.RenewalDate,
			&i.Nominee,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentTxByInvestment = `-- name: ListInvestmentTxByInvestment :many
SELECT id, investment_id, type, quantity, price, amount, date, note, created_at, deleted_at FROM investment_transactions WHERE investment_id = $1 AND deleted_at IS NULL ORDER BY date DESC
`

// Investment Transactions
func (q *Queries) ListInvestmentTxByInvestment(ctx context.Context, investmentID pgtype.UUID) ([]InvestmentTransaction, error) {
	rows, err := q.db.Query(ctx, listInvestmentTxByInvestment, investmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestmentTransaction{}
	for rows.Next() {
		var i InvestmentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.Type,
			&i.Quantity,
			&i.Price,
			&i.Amount,
			&i.Date,
			&i.Note,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByUser = `-- name: ListInvestmentsByUser :many
SELECT id, user_id, name, asset_type, currency, quantity, buy_price, current_price, current_price_updated_at, maturity_date, interest_rate, metadata, created_at, updated_at, deleted_at FROM investments WHERE user_id = $1 AND deleted_at IS NULL ORDER BY name
`

// Investments
func (q *Queries) ListInvestmentsByUser(ctx context.Context, userID pgtype.UUID) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investment{}
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AssetType,
			&i.Currency,
			&i.Quantity,
			&i.BuyPrice,
			&i.CurrentPrice,
			&i.CurrentPriceUpdatedAt,
			&i.MaturityDate,
			&i.InterestRate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanPayments = `-- name: ListLoanPayments :many
SELECT id, loan_id, date, amount, principal_component, interest_component, status, created_at, deleted_at FROM loan_payments WHERE loan_id = $1 AND deleted_at IS NULL ORDER BY date DESC
`

// Loan Payments
func (q *Queries) ListLoanPayments(ctx context.Context, loanID pgtype.UUID) ([]LoanPayment, error) {
	rows, err := q.db.Query(ctx, listLoanPayments, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanPayment{}
	for rows.Next() {
		var i LoanPayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.Date,
			&i.Amount,
			&i.PrincipalComponent,
			&i.InterestComponent,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByUser = `-- name: ListLoansByUser :many
SELECT id, user_id, name, loan_type, principal, interest_rate, tenure_months, start_date, emi_amount, currency, outstanding_balance, created_at, updated_at, deleted_at FROM loans WHERE user_id = $1 AND deleted_at IS NULL ORDER BY name
`

// Loans
func (q *Queries) ListLoansByUser(ctx context.Context, userID pgtype.UUID) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LoanType,
			&i.Principal,
			&i.InterestRate,
			&i.TenureMonths,
			&i.StartDate,
			&i.EmiAmount,
			&i.Currency,
			&i.OutstandingBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoalsByUser = `-- name: ListSavingsGoalsByUser :many
SELECT id, user_id, name, description, target_amount, currency, current_amount, linked_account_id, deadline, status, created_at, updated_at, deleted_at FROM savings_goals WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

// Savings Goals
func (q *Queries) ListSavingsGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.TargetAmount,
			&i.Currency,
			&i.CurrentAmount,
			&i.LinkedAccountID,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, user_id, name, color FROM tags WHERE user_id = $1 ORDER BY name
`

// Tags
func (q *Queries) ListTagsByUser(ctx context.Context, userID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT t.id, t.user_id, t.account_id, t.type, t.amount, t.currency, t.converted_amount, t.base_currency, t.category_id, t.title, t.note, t.date, t.is_recurring, t.recurrence_rule, t.recurrence_interval, t.recurrence_unit, t.parent_recurring_id, t.transfer_to_id, t.created_at, t.updated_at, t.deleted_at, a.name as account_name, c.name as category_name,
  COALESCE(json_agg(json_build_object('id', tg.id, 'name', tg.name, 'color', tg.color))
    FILTER (WHERE tg.id IS NOT NULL), '[]') as tags
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN transaction_tags tt ON tt.transaction_id = t.id
LEFT JOIN tags tg ON tg.id = tt.tag_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL
  AND ($2::text IS NULL OR t.type::text = $2)
  AND ($3::uuid IS NULL OR t.account_id = $3)
  AND ($4::date IS NULL OR t.date >= $4)
  AND ($5::date IS NULL OR t.date <= $5)
GROUP BY t.id, a.name, c.name
ORDER BY t.date DESC
LIMIT $6::int
`

type ListTransactionsByUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Type      pgtype.Text `json:"type"`
	AccountID pgtype.UUID `json:"account_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
	LimitRows pgtype.Int4 `json:"limit_rows"`
}

type ListTransactionsByUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	Type               TransactionType    `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ConvertedAmount    pgtype.Numeric     `json:"converted_amount"`
	BaseCurrency       pgtype.Text        `json:"base_currency"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Title              pgtype.Text        `json:"title"`
	Note               pgtype.Text        `json:"note"`
	Date               pgtype.Date        `json:"date"`
	IsRecurring        bool               `json:"is_recurring"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric     `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text        `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID        `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID        `json:"transfer_to_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	AccountName        string             `json:"account_name"`
	CategoryName       pgtype.Text        `json:"category_name"`
	Tags               interface{}        `json:"tags"`
}

// Transactions
func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser,
		arg.UserID,
		arg.Type,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByUserRow{}
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.ConvertedAmount,
			&i.BaseCurrency,
			&i.CategoryID,
			&i.Title,
			&i.Note,
			&i.Date,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceInterval,
			&i.RecurrenceUnit,
			&i.ParentRecurringID,
			&i.TransferToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountName,
			&i.CategoryName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionTags = `-- name: SetTransactionTags :exec
DELETE FROM transaction_tags WHERE transaction_id = $1
`

func (q *Queries) SetTransactionTags(ctx context.Context, transactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setTransactionTags, transactionID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET name = $2, type = $3, currency = $4, opening_balance = $5, credit_limit = $6, statement_day = $7, payment_due_day = $8, updated_at = now()
WHERE id = $1 AND user_id = $9 AND deleted_at IS NULL RETURNING id, user_id, name, type, currency, opening_balance, credit_limit, statement_day, payment_due_day, created_at, updated_at, deleted_at
`

type UpdateAccountParams struct {
	ID             pgtype.UUID    `json:"id"`
	Name           string         `json:"name"`
	Type           AccountType    `json:"type"`
	Currency       string         `json:"currency"`
	OpeningBalance pgtype.Numeric `json:"opening_balance"`
	CreditLimit    pgtype.Numeric `json:"credit_limit"`
	StatementDay   pgtype.Numeric `json:"statement_day"`
	PaymentDueDay  pgtype.Numeric `json:"payment_due_day"`
	UserID         pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.CreditLimit,
		arg.StatementDay,
		arg.PaymentDueDay,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.CreditLimit,
		&i.StatementDay,
		&i.PaymentDueDay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets SET category_id = $2, name = $3, amount = $4, currency = $5,
  period_type = $6, start_date = $7, end_date = $8, period_anchor_date = $9,
  rollover = $10, updated_at = now()
WHERE id = $1 AND user_id = $11 AND deleted_at IS NULL RETURNING id, user_id, category_id, name, amount, currency, period_type, start_date, end_date, period_anchor_date, rollover, created_at, updated_at, deleted_at
`

type UpdateBudgetParams struct {
	ID               pgtype.UUID    `json:"id"`
	CategoryID       pgtype.UUID    `json:"category_id"`
	Name             string         `json:"name"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	PeriodType       PeriodType     `json:"period_type"`
	StartDate        pgtype.Date    `json:"start_date"`
	EndDate          pgtype.Date    `json:"end_date"`
	PeriodAnchorDate pgtype.Date    `json:"period_anchor_date"`
	Rollover         bool           `json:"rollover"`
	UserID           pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.PeriodType,
		arg.StartDate,
		arg.EndDate,
		arg.PeriodAnchorDate,
		arg.Rollover,
		arg.UserID,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.PeriodType,
		&i.StartDate,
		&i.EndDate,
		&i.PeriodAnchorDate,
		&i.Rollover,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $2, type = $3, icon = $4, color = $5
WHERE id = $1 AND user_id = $6 AND deleted_at IS NULL RETURNING id, user_id, name, type, icon, color, deleted_at
`

type UpdateCategoryParams struct {
	ID     pgtype.UUID  `json:"id"`
	Name   string       `json:"name"`
	Type   CategoryType `json:"type"`
	Icon   pgtype.Text  `json:"icon"`
	Color  pgtype.Text  `json:"color"`
	UserID pgtype.UUID  `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
	)
	return i, err
}

const updateInsurancePolicy = `-- name: UpdateInsurancePolicy :one
UPDATE insurance_policies SET name = $2, provider = $3, policy_type = $4, premium_amount = $5,
  premium_frequency = $6, coverage_amount = $7, currency = $8, start_date = $9,
  end_date = $10, renewal_date = $11, nominee = $12, notes = $13, updated_at = now()
WHERE id = $1 AND user_id = $14 AND deleted_at IS NULL RETURNING id, user_id, name, provider, policy_type, premium_amount, premium_frequency, coverage_amount, currency, start_date, end_date, renewal_date, nominee, notes, created_at, updated_at, deleted_at
`

type UpdateInsurancePolicyParams struct {
	ID               pgtype.UUID      `json:"id"`
	Name             string           `json:"name"`
	Provider         pgtype.Text      `json:"provider"`
	PolicyType       PolicyType       `json:"policy_type"`
	PremiumAmount    pgtype.Numeric   `json:"premium_amount"`
	PremiumFrequency PremiumFrequency `json:"premium_frequency"`
	CoverageAmount   pgtype.Numeric   `json:"coverage_amount"`
	Currency         string           `json:"currency"`
	StartDate        pgtype.Date      `json:"start_date"`
	EndDate          pgtype.Date      `json:"end_date"`
	RenewalDate      pgtype.Date      `json:"renewal_date"`
	Nominee          pgtype.Text      `json:"nominee"`
	Notes            pgtype.Text      `json:"notes"`
	UserID           pgtype.UUID      `json:"user_id"`
}

func (q *Queries) UpdateInsurancePolicy(ctx context.Context, arg UpdateInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, updateInsurancePolicy,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.PolicyType,
		arg.PremiumAmount,
		arg.PremiumFrequency,
		arg.CoverageAmount,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.RenewalDate,
		arg.Nominee,
		arg.Notes,
		arg.UserID,
	)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.PolicyType,
		&i.PremiumAmount,
		&i.PremiumFrequency,
		&i.CoverageAmount,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.RenewalDate,
		&i.Nominee,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvestment = `-- name: UpdateInvestment :one
UPDATE investments SET name = $2, asset_type = $3, currency = $4, quantity = $5,
  buy_price = $6, current_price = $7, current_price_updated_at = $8, maturity_date = $9,
  interest_rate = $10, metadata = $11, updated_at = now()
WHERE id = $1 AND user_id = $12 AND deleted_at IS NULL RETURNING id, user_id, name, asset_type, currency, quantity, buy_price, current_price, current_price_updated_at, maturity_date, interest_rate, metadata, created_at, updated_at, deleted_at
`

type UpdateInvestmentParams struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	AssetType             AssetType          `json:"asset_type"`
	Currency              string             `json:"currency"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	BuyPrice              pgtype.Numeric     `json:"buy_price"`
	CurrentPrice          pgtype.Numeric     `json:"current_price"`
	CurrentPriceUpdatedAt pgtype.Timestamptz `json:"current_price_updated_at"`
	MaturityDate          pgtype.Date        `json:"maturity_date"`
	InterestRate          pgtype.Numeric     `json:"interest_rate"`
	Metadata              []byte             `json:"metadata"`
	UserID                pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, updateInvestment,
		arg.ID,
		arg.Name,
		arg.AssetType,
		arg.Currency,
		arg.Quantity,
		arg.BuyPrice,
		arg.CurrentPrice,
		arg.CurrentPriceUpdatedAt,
		arg.MaturityDate,
		arg.InterestRate,
		arg.Metadata,
		arg.UserID,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.Currency,
		&i.Quantity,
		&i.BuyPrice,
		&i.CurrentPrice,
		&i.CurrentPriceUpdatedAt,
		&i.MaturityDate,
		&i.InterestRate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLoan = `-- name: UpdateLoan :one
UPDATE loans SET name = $2, loan_type = $3, principal = $4, interest_rate = $5,
  tenure_months = $6, start_date = $7, emi_amount = $8, currency = $9,
  outstanding_balance = $10, updated_at = now()
WHERE id = $1 AND user_id = $11 AND deleted_at IS NULL RETURNING id, user_id, name, loan_type, principal, interest_rate, tenure_months, start_date, emi_amount, currency, outstanding_balance, created_at, updated_at, deleted_at
`

type UpdateLoanParams struct {
	ID                 pgtype.UUID    `json:"id"`
	Name               string         `json:"name"`
	LoanType           LoanType       `json:"loan_type"`
	Principal          pgtype.Numeric `json:"principal"`
	InterestRate       pgtype.Numeric `json:"interest_rate"`
	TenureMonths       int32          `json:"tenure_months"`
	StartDate          pgtype.Date    `json:"start_date"`
	EmiAmount          pgtype.Numeric `json:"emi_amount"`
	Currency           string         `json:"currency"`
	OutstandingBalance pgtype.Numeric `json:"outstanding_balance"`
	UserID             pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoan,
		arg.ID,
		arg.Name,
		arg.LoanType,
		arg.Principal,
		arg.InterestRate,
		arg.TenureMonths,
		arg.StartDate,
		arg.EmiAmount,
		arg.Currency,
		arg.OutstandingBalance,
		arg.UserID,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LoanType,
		&i.Principal,
		&i.InterestRate,
		&i.TenureMonths,
		&i.StartDate,
		&i.EmiAmount,
		&i.Currency,
		&i.OutstandingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals SET name = $2, description = $3, target_amount = $4, currency = $5,
  current_amount = $6, linked_account_id = $7, deadline = $8, status = $9, updated_at = now()
WHERE id = $1 AND user_id = $10 AND deleted_at IS NULL RETURNING id, user_id, name, description, target_amount, currency, current_amount, linked_account_id, deadline, status, created_at, updated_at, deleted_at
`

type UpdateSavingsGoalParams struct {
	ID              pgtype.UUID    `json:"id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	TargetAmount    pgtype.Numeric `json:"target_amount"`
	Currency        string         `json:"currency"`
	CurrentAmount   pgtype.Numeric `json:"current_amount"`
	LinkedAccountID pgtype.UUID    `json:"linked_account_id"`
	Deadline        pgtype.Date    `json:"deadline"`
	Status          GoalStatus     `json:"status"`
	UserID          pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TargetAmount,
		arg.Currency,
		arg.CurrentAmount,
		arg.LinkedAccountID,
		arg.Deadline,
		arg.Status,
		arg.UserID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.Currency,
		&i.CurrentAmount,
		&i.LinkedAccountID,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET account_id = $2, type = $3, amount = $4, currency = $5,
  converted_amount = $6, base_currency = $7, category_id = $8, title = $9, note = $10,
  date = $11, is_recurring = $12, updated_at = now()
WHERE id = $1 AND user_id = $13 AND deleted_at IS NULL RETURNING id, user_id, account_id, type, amount, currency, converted_amount, base_currency, category_id, title, note, date, is_recurring, recurrence_rule, recurrence_interval, recurrence_unit, parent_recurring_id, transfer_to_id, created_at, updated_at, deleted_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID     `json:"id"`
	AccountID       pgtype.UUID     `json:"account_id"`
	Type            TransactionType `json:"type"`
	Amount          pgtype.Numeric  `json:"amount"`
	Currency        string          `json:"currency"`
	ConvertedAmount pgtype.Numeric  `json:"converted_amount"`
	BaseCurrency    pgtype.Text     `json:"base_currency"`
	CategoryID      pgtype.UUID     `json:"category_id"`
	Title           pgtype.Text     `json:"title"`
	Note            pgtype.Text     `json:"note"`
	Date            pgtype.Date     `json:"date"`
	IsRecurring     bool            `json:"is_recurring"`
	UserID          pgtype.UUID     `json:"user_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.ConvertedAmount,
		arg.BaseCurrency,
		arg.CategoryID,
		arg.Title,
		arg.Note,
		arg.Date,
		arg.IsRecurring,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.ConvertedAmount,
		&i.BaseCurrency,
		&i.CategoryID,
		&i.Title,
		&i.Note,
		&i.Date,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.RecurrenceInterval,
		&i.RecurrenceUnit,
		&i.ParentRecurringID,
		&i.TransferToID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, default_currency = $3, timezone = $4, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL RETURNING id, email, password_hash, name, default_currency, timezone, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	DefaultCurrency string      `json:"default_currency"`
	Timezone        string      `json:"timezone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.DefaultCurrency,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (base, target, rate, fetched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (base, target) DO UPDATE SET rate = $3, fetched_at = $4
`

type UpsertExchangeRateParams struct {
	Base      string             `json:"base"`
	Target    string             `json:"target"`
	Rate      pgtype.Numeric     `json:"rate"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

// Exchange Rates
func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate,
		arg.Base,
		arg.Target,
		arg.Rate,
		arg.FetchedAt,
	)
	return err
}
