// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeBank       AccountType = "bank"
	AccountTypeWallet     AccountType = "wallet"
	AccountTypeCash       AccountType = "cash"
	AccountTypeSavings    AccountType = "savings"
	AccountTypeCreditCard AccountType = "credit_card"
	AccountTypeInvestment AccountType = "investment"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type AssetType string

const (
	AssetTypeStock      AssetType = "stock"
	AssetTypeMf         AssetType = "mf"
	AssetTypeCrypto     AssetType = "crypto"
	AssetTypeFd         AssetType = "fd"
	AssetTypePpf        AssetType = "ppf"
	AssetTypeNps        AssetType = "nps"
	AssetTypeGold       AssetType = "gold"
	AssetTypeSilver     AssetType = "silver"
	AssetTypeRealEstate AssetType = "real_estate"
	AssetTypeSavings    AssetType = "savings"
	AssetTypeOther      AssetType = "other"
)

func (e *AssetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetType(s)
	case string:
		*e = AssetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetType: %T", src)
	}
	return nil
}

type NullAssetType struct {
	AssetType AssetType `json:"asset_type"`
	Valid     bool      `json:"valid"` // Valid is true if AssetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetType), nil
}

type AuditAction string

const (
	AuditActionCreate AuditAction = "create"
	AuditActionUpdate AuditAction = "update"
	AuditActionDelete AuditAction = "delete"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type CategoryType string

const (
	CategoryTypeIncome  CategoryType = "income"
	CategoryTypeExpense CategoryType = "expense"
)

func (e *CategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryType(s)
	case string:
		*e = CategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryType: %T", src)
	}
	return nil
}

type NullCategoryType struct {
	CategoryType CategoryType `json:"category_type"`
	Valid        bool         `json:"valid"` // Valid is true if CategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryType), nil
}

type GoalStatus string

const (
	GoalStatusActive    GoalStatus = "active"
	GoalStatusAchieved  GoalStatus = "achieved"
	GoalStatusAbandoned GoalStatus = "abandoned"
)

func (e *GoalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoalStatus(s)
	case string:
		*e = GoalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GoalStatus: %T", src)
	}
	return nil
}

type NullGoalStatus struct {
	GoalStatus GoalStatus `json:"goal_status"`
	Valid      bool       `json:"valid"` // Valid is true if GoalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GoalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoalStatus), nil
}

type InsurancePaymentStatus string

const (
	InsurancePaymentStatusPaid   InsurancePaymentStatus = "paid"
	InsurancePaymentStatusDue    InsurancePaymentStatus = "due"
	InsurancePaymentStatusMissed InsurancePaymentStatus = "missed"
)

func (e *InsurancePaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InsurancePaymentStatus(s)
	case string:
		*e = InsurancePaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InsurancePaymentStatus: %T", src)
	}
	return nil
}

type NullInsurancePaymentStatus struct {
	InsurancePaymentStatus InsurancePaymentStatus `json:"insurance_payment_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if InsurancePaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInsurancePaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InsurancePaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InsurancePaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInsurancePaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InsurancePaymentStatus), nil
}

type InvestmentTxType string

const (
	InvestmentTxTypeBuy      InvestmentTxType = "buy"
	InvestmentTxTypeSell     InvestmentTxType = "sell"
	InvestmentTxTypeDividend InvestmentTxType = "dividend"
	InvestmentTxTypeInterest InvestmentTxType = "interest"
	InvestmentTxTypeBonus    InvestmentTxType = "bonus"
)

func (e *InvestmentTxType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvestmentTxType(s)
	case string:
		*e = InvestmentTxType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvestmentTxType: %T", src)
	}
	return nil
}

type NullInvestmentTxType struct {
	InvestmentTxType InvestmentTxType `json:"investment_tx_type"`
	Valid            bool             `json:"valid"` // Valid is true if InvestmentTxType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvestmentTxType) Scan(value interface{}) error {
	if value == nil {
		ns.InvestmentTxType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvestmentTxType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvestmentTxType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvestmentTxType), nil
}

type LoanType string

const (
	LoanTypeHome      LoanType = "home"
	LoanTypePersonal  LoanType = "personal"
	LoanTypeVehicle   LoanType = "vehicle"
	LoanTypeEducation LoanType = "education"
	LoanTypeOther     LoanType = "other"
)

func (e *LoanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanType(s)
	case string:
		*e = LoanType(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanType: %T", src)
	}
	return nil
}

type NullLoanType struct {
	LoanType LoanType `json:"loan_type"`
	Valid    bool     `json:"valid"` // Valid is true if LoanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanType) Scan(value interface{}) error {
	if value == nil {
		ns.LoanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanType), nil
}

type PaymentStatus string

const (
	PaymentStatusScheduled PaymentStatus = "scheduled"
	PaymentStatusPaid      PaymentStatus = "paid"
	PaymentStatusMissed    PaymentStatus = "missed"
	PaymentStatusPartial   PaymentStatus = "partial"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PeriodType string

const (
	PeriodTypeMonthly PeriodType = "monthly"
	PeriodTypeWeekly  PeriodType = "weekly"
)

func (e *PeriodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PeriodType(s)
	case string:
		*e = PeriodType(s)
	default:
		return fmt.Errorf("unsupported scan type for PeriodType: %T", src)
	}
	return nil
}

type NullPeriodType struct {
	PeriodType PeriodType `json:"period_type"`
	Valid      bool       `json:"valid"` // Valid is true if PeriodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriodType) Scan(value interface{}) error {
	if value == nil {
		ns.PeriodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PeriodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PeriodType), nil
}

type PolicyType string

const (
	PolicyTypeLife     PolicyType = "life"
	PolicyTypeHealth   PolicyType = "health"
	PolicyTypeVehicle  PolicyType = "vehicle"
	PolicyTypeProperty PolicyType = "property"
	PolicyTypeTerm     PolicyType = "term"
	PolicyTypeOther    PolicyType = "other"
)

func (e *PolicyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PolicyType(s)
	case string:
		*e = PolicyType(s)
	default:
		return fmt.Errorf("unsupported scan type for PolicyType: %T", src)
	}
	return nil
}

type NullPolicyType struct {
	PolicyType PolicyType `json:"policy_type"`
	Valid      bool       `json:"valid"` // Valid is true if PolicyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPolicyType) Scan(value interface{}) error {
	if value == nil {
		ns.PolicyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PolicyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPolicyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PolicyType), nil
}

type PremiumFrequency string

const (
	PremiumFrequencyMonthly   PremiumFrequency = "monthly"
	PremiumFrequencyQuarterly PremiumFrequency = "quarterly"
	PremiumFrequencyAnnual    PremiumFrequency = "annual"
)

func (e *PremiumFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PremiumFrequency(s)
	case string:
		*e = PremiumFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for PremiumFrequency: %T", src)
	}
	return nil
}

type NullPremiumFrequency struct {
	PremiumFrequency PremiumFrequency `json:"premium_frequency"`
	Valid            bool             `json:"valid"` // Valid is true if PremiumFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPremiumFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.PremiumFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PremiumFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPremiumFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PremiumFrequency), nil
}

type TransactionType string

const (
	TransactionTypeIncome        TransactionType = "income"
	TransactionTypeExpense       TransactionType = "expense"
	TransactionTypeTransfer      TransactionType = "transfer"
	TransactionTypeCreditPayment TransactionType = "credit_payment"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Account struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	Type           AccountType        `json:"type"`
	Currency       string             `json:"currency"`
	OpeningBalance pgtype.Numeric     `json:"opening_balance"`
	CreditLimit    pgtype.Numeric     `json:"credit_limit"`
	StatementDay   pgtype.Numeric     `json:"statement_day"`
	PaymentDueDay  pgtype.Numeric     `json:"payment_due_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     AuditAction        `json:"action"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Budget struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	PeriodType       PeriodType         `json:"period_type"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	PeriodAnchorDate pgtype.Date        `json:"period_anchor_date"`
	Rollover         bool               `json:"rollover"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Type      CategoryType       `json:"type"`
	Icon      pgtype.Text        `json:"icon"`
	Color     pgtype.Text        `json:"color"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type CategoryKeyword struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Keyword    string             `json:"keyword"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ExchangeRate struct {
	Base      string             `json:"base"`
	Target    string             `json:"target"`
	Rate      pgtype.Numeric     `json:"rate"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type InsurancePayment struct {
	ID        pgtype.UUID            `json:"id"`
	PolicyID  pgtype.UUID            `json:"policy_id"`
	Date      pgtype.Date            `json:"date"`
	Amount    pgtype.Numeric         `json:"amount"`
	Status    InsurancePaymentStatus `json:"status"`
	CreatedAt pgtype.Timestamptz     `json:"created_at"`
	DeletedAt pgtype.Timestamptz     `json:"deleted_at"`
}

type InsurancePolicy struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Name             string             `json:"name"`
	Provider         pgtype.Text        `json:"provider"`
	PolicyType       PolicyType         `json:"policy_type"`
	PremiumAmount    pgtype.Numeric     `json:"premium_amount"`
	PremiumFrequency PremiumFrequency   `json:"premium_frequency"`
	CoverageAmount   pgtype.Numeric     `json:"coverage_amount"`
	Currency         string             `json:"currency"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	RenewalDate      pgtype.Date        `json:"renewal_date"`
	Nominee          pgtype.Text        `json:"nominee"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type Investment struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	Name                  string             `json:"name"`
	AssetType             AssetType          `json:"asset_type"`
	Currency              string             `json:"currency"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	BuyPrice              pgtype.Numeric     `json:"buy_price"`
	CurrentPrice          pgtype.Numeric     `json:"current_price"`
	CurrentPriceUpdatedAt pgtype.Timestamptz `json:"current_price_updated_at"`
	MaturityDate          pgtype.Date        `json:"maturity_date"`
	InterestRate          pgtype.Numeric     `json:"interest_rate"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type InvestmentTransaction struct {
	ID           pgtype.UUID        `json:"id"`
	InvestmentID pgtype.UUID        `json:"investment_id"`
	Type         InvestmentTxType   `json:"type"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Price        pgtype.Numeric     `json:"price"`
	Amount       pgtype.Numeric     `json:"amount"`
	Date         pgtype.Date        `json:"date"`
	Note         pgtype.Text        `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Loan struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Name               string             `json:"name"`
	LoanType           LoanType           `json:"loan_type"`
	Principal          pgtype.Numeric     `json:"principal"`
	InterestRate       pgtype.Numeric     `json:"interest_rate"`
	TenureMonths       int32              `json:"tenure_months"`
	StartDate          pgtype.Date        `json:"start_date"`
	EmiAmount          pgtype.Numeric     `json:"emi_amount"`
	Currency           string             `json:"currency"`
	OutstandingBalance pgtype.Numeric     `json:"outstanding_balance"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type LoanPayment struct {
	ID                 pgtype.UUID        `json:"id"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	Date               pgtype.Date        `json:"date"`
	Amount             pgtype.Numeric     `json:"amount"`
	PrincipalComponent pgtype.Numeric     `json:"principal_component"`
	InterestComponent  pgtype.Numeric     `json:"interest_component"`
	Status             PaymentStatus      `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type SavingsGoal struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	TargetAmount    pgtype.Numeric     `json:"target_amount"`
	Currency        string             `json:"currency"`
	CurrentAmount   pgtype.Numeric     `json:"current_amount"`
	LinkedAccountID pgtype.UUID        `json:"linked_account_id"`
	Deadline        pgtype.Date        `json:"deadline"`
	Status          GoalStatus         `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Tag struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Color  pgtype.Text `json:"color"`
}

type Transaction struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	Type               TransactionType    `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ConvertedAmount    pgtype.Numeric     `json:"converted_amount"`
	BaseCurrency       pgtype.Text        `json:"base_currency"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Title              pgtype.Text        `json:"title"`
	Note               pgtype.Text        `json:"note"`
	Date               pgtype.Date        `json:"date"`
	IsRecurring        bool               `json:"is_recurring"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	RecurrenceInterval pgtype.Numeric     `json:"recurrence_interval"`
	RecurrenceUnit     pgtype.Text        `json:"recurrence_unit"`
	ParentRecurringID  pgtype.UUID        `json:"parent_recurring_id"`
	TransferToID       pgtype.UUID        `json:"transfer_to_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type TransactionTag struct {
	TransactionID pgtype.UUID `json:"transaction_id"`
	TagID         pgtype.UUID `json:"tag_id"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Name            string             `json:"name"`
	DefaultCurrency string             `json:"default_currency"`
	Timezone        string             `json:"timezone"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
