// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryKeyword(ctx context.Context, arg CreateCategoryKeywordParams) (CategoryKeyword, error)
	CreateInsurancePayment(ctx context.Context, arg CreateInsurancePaymentParams) (InsurancePayment, error)
	CreateInsurancePolicy(ctx context.Context, arg CreateInsurancePolicyParams) (InsurancePolicy, error)
	CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error)
	CreateInvestmentTx(ctx context.Context, arg CreateInvestmentTxParams) (InvestmentTransaction, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error)
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteCategoryKeyword(ctx context.Context, arg DeleteCategoryKeywordParams) error
	DeleteInsurancePolicy(ctx context.Context, arg DeleteInsurancePolicyParams) error
	DeleteInvestment(ctx context.Context, arg DeleteInvestmentParams) error
	DeleteLoan(ctx context.Context, arg DeleteLoanParams) error
	DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetBudgetByID(ctx context.Context, id pgtype.UUID) (Budget, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error)
	GetExpensesByPeriod(ctx context.Context, arg GetExpensesByPeriodParams) ([]GetExpensesByPeriodRow, error)
	GetIncomeByPeriod(ctx context.Context, arg GetIncomeByPeriodParams) ([]GetIncomeByPeriodRow, error)
	GetInsurancePolicyByID(ctx context.Context, id pgtype.UUID) (InsurancePolicy, error)
	GetInvestmentByID(ctx context.Context, id pgtype.UUID) (Investment, error)
	GetLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error)
	GetTransactionTags(ctx context.Context, transactionID pgtype.UUID) ([]Tag, error)
	// Summary / aggregation queries
	GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]GetTransactionsByDateRangeRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Users
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Accounts
	ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error)
	// Budgets
	ListBudgetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListBudgetsByUserRow, error)
	// Categories
	ListCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	// Category Keywords (for auto-categorisation)
	ListCategoryKeywordsByUser(ctx context.Context, userID pgtype.UUID) ([]ListCategoryKeywordsByUserRow, error)
	ListExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	// Insurance Payments
	ListInsurancePayments(ctx context.Context, policyID pgtype.UUID) ([]InsurancePayment, error)
	// Insurance Policies
	ListInsurancePoliciesByUser(ctx context.Context, userID pgtype.UUID) ([]InsurancePolicy, error)
	// Investment Transactions
	ListInvestmentTxByInvestment(ctx context.Context, investmentID pgtype.UUID) ([]InvestmentTransaction, error)
	// Investments
	ListInvestmentsByUser(ctx context.Context, userID pgtype.UUID) ([]Investment, error)
	// Loan Payments
	ListLoanPayments(ctx context.Context, loanID pgtype.UUID) ([]LoanPayment, error)
	// Loans
	ListLoansByUser(ctx context.Context, userID pgtype.UUID) ([]Loan, error)
	// Savings Goals
	ListSavingsGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]SavingsGoal, error)
	// Tags
	ListTagsByUser(ctx context.Context, userID pgtype.UUID) ([]Tag, error)
	// Transactions
	ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error)
	SetTransactionTags(ctx context.Context, transactionID pgtype.UUID) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInsurancePolicy(ctx context.Context, arg UpdateInsurancePolicyParams) (InsurancePolicy, error)
	UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error)
	UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error)
	UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Exchange Rates
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
}

var _ Querier = (*Queries)(nil)
